### ISSUE TITLE
Cat 4 ESP32 to control vfo SI351

### ISSUE THREAD

**Issue by yo2ldk** [pavelmc/FT857d#7]

**Comment by pavelmc** [comment]
Hi alexander!

You mentioned the error in your email.

You can't remove any frunction and must integrate ALL functions in the sketch as ANY program will try to check all features on first connection, if any of the features fail, then it will not work.

If you want send me the sketch to take a peek in your code and help.

cheers

14 de diciembre de 2020 16:43, "alexander - yo2ldk" <notifications@github.com (mailto:notifications@github.com?to=%22alexander%20-%20yo2ldk%22%20<notifications@github.com>)> escribió:
	Hello Pavel, 

	I have an SDR receiver with SI5351 as VFO, controlled by ESP32 with encoder
and try it your nice work to add on my ino file to have possibility
on HDSDR software to see and modify frequency from computer to Si5351 via ESP32
but, something is wrong, I have communications is connected as FT857 but frequency is locked or not change it
Have some tips to help me?
p.s. I removed other functions and keep it only part for frequency 

	TNX in advance and my best 73 !

**Comment by yo2ldk** [comment]
Hello Pavel,

Thank you for reply and your kindness, sorry for  response, holidays..
 I not refer at one error with your software, but in my trying to adapt for my needs;
 to insert / adapt your code in a VFO file.
 here is the link for .ino file, is an very nice VFO with analog scale on LCD, maybe you find also useful for you, will be nice to complete with your CAT to follow the SDR software
 
 https://github.com/tjlab-jf3hzb/Digital_VFO_with_analog_dial/tree/master/VFOsys
 
 this it is and I have it on my SDR receiver project, but SDR harp is not synchronized because not have CAT
 here is a little video
 https://twitter.com/i/status/1335678924186120193
 
  Thank you in advance !
