### ISSUE TITLE
Debugging and serial ports

### ISSUE THREAD

**Issue by KA1GT** [pavelmc/FT857d#9]
Forgive me if I'm missing something, but I can't see howto get the debug feature to work.  As far as I can tell, the library is written using the on-board serial port. So communication from software running on the PC uses this Arduino port to talk with the simulator. That works just fine. 

However if debugging is enables, the debug messages also try to use the same serial port to talk back with the Arduino IDE for display in the serial monitor window.  If the software on the PC which is talking with the emulator has control of that port, then the Arduino IDE cant access it. Indeed if I enable debugging I get an error message "Error opening serial port 'COM19'. (Port busy)" showing the port is unavailable since it's in use.

If I want to use the serial monitor function in the Arduino IDE, it appears I would have to rewrite the library using, for example, the serial1, serial2 or serial3 ports of an Arduino Mega or a software defined port on a Uno. Alternatively I guess I could change the debug commands to use a different serial port and use some other terminal emulation software hooked up to that port.

Am I missing something here, or is this the way it works.  Perhaps the program I have talking with the emulator is holding onto the serial port when it shouldn't?  I'm not all that familiar with techniques for sharing a serial port between multiple programs (which I did not write!).

**Comment by stdevPavelmc** [comment]
Hi Bob, 

In the example code it tells it clearly:

```C++
// DEBUG flag, uncomment it if you want to test it by hand
//#define DEBUG true
```
That option is there to test it **by hand**, aka: sending the commands yourself on the serial line from a serial terminal; there is no provision to use another serial port for that, but as yourself mentioned, nothing stop you for doing just that.

Cheers

**Comment by KA1GT** [comment]
Thanks for the clarification.  It's also possible to see what's going using a single com port using Eltima's Serial Port Monitor
